"""baseline schema

Revision ID: bb1a61d49502
Revises:
Create Date: 2026-08-27 09:56:16.747413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb1a61d49502"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("plan", sa.String(length=20), server_default="free", nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("max_users", sa.Integer(), server_default="5", nullable=False),
        sa.Column("max_categories", sa.Integer(), server_default="10", nullable=False),
        sa.Column("max_sources", sa.Integer(), server_default="50", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("plan IN ('free', 'pro', 'enterprise')", name="chk_tenants_plan"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "categories",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("icon", sa.String(length=50), server_default="folder", nullable=True),
        sa.Column("color", sa.String(length=7), server_default=sa.text("'#3B82F6'"), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("refresh_interval_seconds", sa.Integer(), server_default="300", nullable=False),
        sa.Column(
            "keywords_filter",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column("priority_sort", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("type IN ('finance', 'tech', 'news', 'custom')", name="chk_categories_type"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_categories_tenant_slug"),
    )
    op.create_index("idx_categories_tenant", "categories", ["tenant_id"], unique=False)
    op.create_index("idx_categories_type", "categories", ["tenant_id", "type"], unique=False)
    op.create_table(
        "dashboard_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("cpu_usage_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("memory_used_mb", sa.Integer(), nullable=True),
        sa.Column("memory_total_mb", sa.Integer(), nullable=True),
        sa.Column("disk_used_gb", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("disk_total_gb", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("active_sse_connections", sa.Integer(), nullable=True),
        sa.Column("events_pushed_hour", sa.Integer(), nullable=True),
        sa.Column("healthy_sources", sa.Integer(), nullable=True),
        sa.Column("degraded_sources", sa.Integer(), nullable=True),
        sa.Column("down_sources", sa.Integer(), nullable=True),
        sa.Column("scheduler_jobs_active", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_dashboard_snapshots_time", "dashboard_snapshots", ["tenant_id", "timestamp"], unique=False)
    op.create_table(
        "finance_symbols",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("exchange", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'USD'"), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint(
            "type IN ('stock', 'fund', 'index', 'commodity', 'futures', 'currency')", name="chk_finance_symbols_type"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "symbol", name="uq_finance_symbols_tenant_symbol"),
    )
    op.create_index("idx_finance_symbols_market", "finance_symbols", ["tenant_id", "market"], unique=False)
    op.create_index("idx_finance_symbols_type", "finance_symbols", ["tenant_id", "type"], unique=False)
    op.create_table(
        "users",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("sso_provider", sa.String(length=20), nullable=False),
        sa.Column("sso_provider_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="member", nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'member', 'viewer')", name="chk_users_role"),
        sa.CheckConstraint(
            "sso_provider IN ('google', 'azure_ad', 'github', 'apple', 'facebook', 'local')",
            name="chk_users_sso_provider",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sso_provider", "sso_provider_id", name="uq_users_sso"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    op.create_index("idx_users_sso", "users", ["sso_provider", "sso_provider_id"], unique=False)
    op.create_index("idx_users_tenant", "users", ["tenant_id"], unique=False)
    op.create_table(
        "finance_quotes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.UUID(), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("open_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("high_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("low_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("close_previous", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("change_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("change_percent", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("pe_ratio", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("52_week_high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("52_week_low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_name", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["symbol_id"], ["finance_symbols.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "timestamp"),
        postgresql_partition_by="RANGE (timestamp)",
    )
    op.create_index("idx_finance_quotes_symbol_time", "finance_quotes", ["symbol_id", "timestamp"], unique=False)
    op.create_index("idx_finance_quotes_tenant", "finance_quotes", ["tenant_id"], unique=False)
    op.create_table(
        "fund_nav_estimates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.UUID(), nullable=False),
        sa.Column("nav_official", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("nav_official_date", sa.DATE(), nullable=True),
        sa.Column("nav_estimate", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("nav_estimate_deviation_percent", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("estimate_method", sa.String(length=50), nullable=True),
        sa.Column("estimate_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("underlying_index_symbol", sa.String(length=20), nullable=True),
        sa.Column("underlying_index_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("underlying_index_change_percent", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["symbol_id"], ["finance_symbols.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_fund_nav_symbol", "fund_nav_estimates", ["symbol_id", "estimate_timestamp"], unique=False)
    op.create_table(
        "sources",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("refresh_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="5", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("source_type IN ('rss', 'api', 'web_scrape', 'social')", name="chk_sources_type"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sources_category", "sources", ["category_id"], unique=False)
    op.create_index("idx_sources_tenant", "sources", ["tenant_id"], unique=False)
    op.create_index("idx_sources_type", "sources", ["tenant_id", "source_type"], unique=False)
    op.create_table(
        "sse_connections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "channels", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("connected_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sse_connections_active",
        "sse_connections",
        ["disconnected_at"],
        unique=False,
        postgresql_where=sa.text("disconnected_at IS NULL"),
    )
    op.create_index("idx_sse_connections_user", "sse_connections", ["user_id"], unique=False)
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.UUID(), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notes", sa.String(length=200), nullable=True),
        sa.Column("alert_threshold_percent", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["symbol_id"], ["finance_symbols.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "symbol_id", name="uq_watchlist_user_symbol"),
    )
    op.create_index("idx_watchlist_user", "watchlist_items", ["user_id", "display_order"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column(
            "topic_tags", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True
        ),
        sa.Column(
            "extra_data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True
        ),
        sa.Column("priority", sa.Integer(), server_default="5", nullable=False),
        sa.Column("is_processed", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_id", "url", "published_at", name="uq_items_dedup"),
    )
    op.create_index("idx_items_category", "items", ["category_id", "published_at"], unique=False)
    op.create_index("idx_items_extra_data", "items", ["extra_data"], unique=False, postgresql_using="gin")
    op.create_index("idx_items_source", "items", ["source_id"], unique=False)
    op.create_index("idx_items_tags", "items", ["topic_tags"], unique=False, postgresql_using="gin")
    op.create_index("idx_items_tenant_time", "items", ["tenant_id", "published_at"], unique=False)
    op.create_table(
        "source_health",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="healthy", nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_fetches_24h", sa.Integer(), server_default="0", nullable=False),
        sa.Column("success_count_24h", sa.Integer(), server_default="0", nullable=False),
        sa.Column("avg_response_time_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("status IN ('healthy', 'degraded', 'down')", name="chk_source_health_status"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_index("idx_source_health_status", "source_health", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_source_health_status", table_name="source_health")
    op.drop_table("source_health")
    op.drop_index("idx_items_tenant_time", table_name="items")
    op.drop_index("idx_items_tags", table_name="items", postgresql_using="gin")
    op.drop_index("idx_items_source", table_name="items")
    op.drop_index("idx_items_extra_data", table_name="items", postgresql_using="gin")
    op.drop_index("idx_items_category", table_name="items")
    op.drop_table("items")
    op.drop_index("idx_watchlist_user", table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index("idx_sse_connections_user", table_name="sse_connections")
    op.drop_index(
        "idx_sse_connections_active", table_name="sse_connections", postgresql_where=sa.text("disconnected_at IS NULL")
    )
    op.drop_table("sse_connections")
    op.drop_index("idx_sources_type", table_name="sources")
    op.drop_index("idx_sources_tenant", table_name="sources")
    op.drop_index("idx_sources_category", table_name="sources")
    op.drop_table("sources")
    op.drop_index("idx_fund_nav_symbol", table_name="fund_nav_estimates")
    op.drop_table("fund_nav_estimates")
    op.drop_index("idx_finance_quotes_tenant", table_name="finance_quotes")
    op.drop_index("idx_finance_quotes_symbol_time", table_name="finance_quotes")
    op.drop_table("finance_quotes")
    op.drop_index("idx_users_tenant", table_name="users")
    op.drop_index("idx_users_sso", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_finance_symbols_type", table_name="finance_symbols")
    op.drop_index("idx_finance_symbols_market", table_name="finance_symbols")
    op.drop_table("finance_symbols")
    op.drop_index("idx_dashboard_snapshots_time", table_name="dashboard_snapshots")
    op.drop_table("dashboard_snapshots")
    op.drop_index("idx_categories_type", table_name="categories")
    op.drop_index("idx_categories_tenant", table_name="categories")
    op.drop_table("categories")
    op.drop_table("tenants")
    # ### end Alembic commands ###
